kind: wasmer.io/App.v0
name: nomad-memories
package: .
description: Private travel memories on an interactive map

env:
  APP_ENV: production
  DATA_DIR: /data

capabilities:
  database:
    engine: postgres

volumes:
  - name: nomad-uploads
    mount: /data

locality:
  regions:
    - fr-roub1

health_checks:
  - path: /health
    method: GET
    interval: 60s
    timeout: 10s
    unhealthy_threshold: 3
    healthy_threshold: 1
    expected_status_codes:
      - 200
